spring:
  application:
    name: commons

jwt:
  secret: thisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkeythisisjwttokensecretkey
  access-token:
    validity-second: 3600
  refresh-token:
    validity-second: 86400
